Repository DistributedCollective/sovryn-monorepo, pull requests merged in 2021-04, with the labels that each got.

#12 Feat/@sovryn/common
  packages/common/README.md
  packages/common/package.json
  packages/common/src/debuggers/index.ts
  packages/common/src/index.ts
  packages/common/tsconfig.json
  packages/common/yarn.lock
  packages/wallet/package.json
  packages/wallet/src/providers/injected-wallet-provider.ts
  packages/wallet/src/providers/ledger-wallet-provider.ts
  packages/wallet/src/providers/portis-wallet-provider.ts
  packages/wallet/src/providers/trezor-wallet-provider.ts
  packages/wallet/src/providers/wallet-connect-provider.ts
  packages/wallet/src/utils/index.ts
  packages/wallet/src/wallet.service.ts
  packages/wallet/src/wallets/ledger/ledger-wallet.ts
  packages/wallet/src/wallets/non-deterministic/web3.ts
  packages/wallet/src/wallets/trezor-wallet.ts
Labels: enhancement, internal

#13 Improved builds
  README.md
  package.json
  packages/react-wallet/example/yarn.lock
  packages/react-wallet/yarn.lock
  packages/wallet/yarn.lock
Labels: internal

#14 Release
  README.md
  lerna.json
  package.json
  packages/common/README.md
  packages/common/package.json
  packages/common/src/debuggers/index.ts
  packages/common/src/index.ts
  packages/common/tsconfig.json
  packages/common/yarn.lock
  packages/react-wallet/example/yarn.lock
  packages/react-wallet/package.json
  packages/react-wallet/src/components/Button/index.tsx
  packages/react-wallet/src/components/Dialog/index.module.css
  packages/react-wallet/src/components/Item/index.module.css
  packages/react-wallet/src/components/Item/index.tsx
  packages/react-wallet/src/components/ProviderDialogSteps/BrowserWalletSelector/index.tsx
  packages/react-wallet/src/components/ProviderDialogSteps/HardwareAddressSelector/index.tsx
  packages/react-wallet/src/components/ProviderDialogSteps/ProviderTypeSelector/index.tsx
  packages/react-wallet/src/containers/ProviderDialog/index.tsx
  packages/react-wallet/src/containers/WalletProvider/index.tsx
  packages/react-wallet/yarn.lock
  packages/wallet/package.json
  packages/wallet/src/dictionaries/network-dictionary.ts
  packages/wallet/src/providers/injected-wallet-provider.ts
  packages/wallet/src/providers/ledger-wallet-provider.ts
  packages/wallet/src/providers/portis-wallet-provider.ts
  packages/wallet/src/providers/trezor-wallet-provider.ts
  packages/wallet/src/providers/wallet-connect-provider.ts
  packages/wallet/src/utils/index.ts
  packages/wallet/src/wallet.service.ts
  packages/wallet/src/wallets/deterministic/deterministic-wallet.ts
  packages/wallet/src/wallets/ledger/ledger-wallet.ts
  packages/wallet/src/wallets/non-deterministic/web3.ts
  packages/wallet/src/wallets/trezor-wallet.ts
  packages/wallet/yarn.lock
Labels: release

#10 Feat/4 custom wallet connect
  lerna.json
  packages/react-wallet/example/package.json
  packages/react-wallet/example/yarn.lock
  packages/react-wallet/package.json
  packages/react-wallet/src/assets/images.ts
  packages/react-wallet/src/assets/wallets/defiant.ts
  packages/react-wallet/src/assets/wallets/rwallet.ts
  packages/react-wallet/src/components/Item/index.module.css
  packages/react-wallet/src/components/Item/index.tsx
  packages/react-wallet/src/components/ProviderDialogSteps/ProviderTypeSelector/index.tsx
  packages/react-wallet/src/components/ProviderDialogSteps/WalletConnectProviders/index.tsx
  packages/react-wallet/src/containers/ProviderDialog/index.tsx
  packages/react-wallet/src/containers/WalletProvider/index.tsx
  packages/react-wallet/src/services/helpers.ts
  packages/react-wallet/yarn.lock
  packages/wallet/package.json
  packages/wallet/src/providers/wallet-connect-provider.ts
  packages/wallet/src/wallets/non-deterministic/wallet-connect-wallet.ts
  packages/wallet/src/wallets/trezor-wallet.ts
Labels: enhancement
